name: Security Scan

on:
  push:

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Snyk Scan

        run: echo "Running Snyk Scan"

      - name: Checkmarx Scan

        run: echo "Running Checkmarx Scan"
